### ISSUE TITLE
Error on view my tickets with staff member show my tickets and show closed tickets

### ISSUE THREAD

**Issue by s3799530** [rob-at-rmit/sepm-a2#3]
I login as a staff member. I view my tickets and gives error message:

1. login user bob / password pwd (test user data)
2. selected option: show my open tickets (option 2)
3. ERROR: That is an invalid selection.
4. select option: Show Closed Tickets (option 3)
5. ERROR: That is an invalid selection.

Suggested solution:

- if it's a staff member don't show closed tickets (original spec)
- if there is no open tickets then don't show option.

It should not matter we jump from option 1 to 4 if there are no open tickets that I own.
If I am not a tech then I shouldn't see closed tickets.

**Comment by rob-at-rmit** [comment]
This doesn't seem to be happening for me. I can log in as bob/pwd and then select option 2.

**Comment by rob-at-rmit** [comment]
Wait, you're saying we should remove the option if they're a staff member?

**Comment by s3799530** [comment]
It was the previous codebased. However, 3 still shows an error and should not be available for staff, only techs.

**Comment by rob-at-rmit** [comment]
Ok.. I don't seem to be able to replicate the error, but I agree, we should restrict the viewing of closed tickets to users that are not in the staff role. I will see if I can do this now.

**Comment by s3799530** [comment]
Here is the spec:

<img width="701" alt="Screen Shot 2020-10-22 at 11 24 09 am" src="https://user-images.githubusercontent.com/51278791/96820718-1e6c7000-1459-11eb-8803-73349b1a72da.png">

Bob is staff and should see closed tickets:

<img width="730" alt="Screen Shot 2020-10-22 at 11 25 12 am" src="https://user-images.githubusercontent.com/51278791/96820788-478d0080-1459-11eb-88d5-c25f592c71e6.png">

Just following the spec... :|

**Comment by s3799530** [comment]
I love what you did with "0" going up a level.

**Comment by s3799530** [comment]
fixed
